# This is a basic workflow to help you get started with Actions

name: Super Linting

# Controls when the workflow will run
on:
  push:
    branches-ignore: [master, main]
    # Remove the line above to run when pushing to master
  pull_request:
    branches: [master, main]
  workflow_dispatch:
  
env:
  GITHUB_WORKSPACE: /

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      ################################
      # Run Linter against code base #
      ################################
      - name: Super-Linter
        uses: github/super-linter/slim@v4.9.4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_WORKSPACE: /
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
